allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: true
  ssh2: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - dompurify@3.4.16
  - imapflow@2.0.6
  - pg-boss@12.33.7
  - prettier@3.9.9
patchedDependencies:
  imapflow@2.0.6: patches/imapflow@2.0.6.patch
  next@16.3.8: patches/next@16.3.8.patch
  pg-boss@12.33.7: patches/pg-boss@12.33.7.patch
overrides:
  mailparser@3.9.28>nodemailer: 10.0.13
  source-map-js@1.2.1: 1.2.2
  sharp@0.35.4: 0.35.5
